name: res-sam
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
dependencies:
  - python=3.9
  - matplotlib
  - numpy<2
  - opencv
  - scikit-learn=1.3
  - scipy<1.14
  - tqdm
  - faiss-cpu
  - pillow
  - pip
  - pip:
    - --index-url https://download.pytorch.org/whl/cu118
    - --extra-index-url https://pypi.org/simple
    - torch==2.3.1+cu118
    - torchvision==0.18.1+cu118
    - torchaudio==2.3.1+cu118
    - git+https://github.com/facebookresearch/segment-anything.git