name: res-sam
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - numpy<2
  - opencv
  - scikit-learn=1.3
  - scipy<1.14
  - tqdm
  - pytorch
  - torchvision
  - cpuonly
  - pillow
  - pip
  - pip:
    - segment-anything
    - faiss-cpu